W10D2/aspiration_list/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show] do 
    resources :goals, only: [:new, :show, :edit, :update, :index]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :goals, only: [:create, :destroy]
end

W10D2/aspiration_list/app/models/goal.rb
class Goal < ApplicationRecord
  validates :name, :user_id, presence: true

  belongs_to(
    :user,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id
  )
end

W10D2/aspiration_list/app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many(
    :goals,
    class_name: 'Goal',
    foreign_key: :user_id,
    primary_key: :id
  )

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    return user if user.is_password?(password)
    nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

W10D2/aspiration_list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  helper_method :current_user

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout!
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def current_user
    # if the sessions session_token is empty, then no one is logged in.
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  private

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_session_url
    end  
  end

end

W10D2/aspiration_list/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id

    if @comment.save
      flash[:notices] = ['Comment saved']
    else
      flash['errors'] = @comment.errors.full_messages
    end

    redirect_back fallback_location: users_url
  end

  private

  def comment_params
    params.require(:comment).permit(:commentable_id, :commentable_type, :body)
  end
end

W10D2/aspiration_list/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @user = User.find_by(id: params[:user_id])
    @goals = Goal.where(user_id: @user.id)

    if @user
      render :index
    else
      @user.errors.full_messages
    end
  end

  def new
    @goal = Goal.new
    @users = User.all
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @users = User.all

    if @goal.save
      redirect_to user_goals_url(@goal.user_id)
    else
      render :new
    end
  end

  def edit
    @goal = Goal.find_by(id: params[:id])

    if @goal
      render :edit
    else
      @goal.errors.full_messages
    end
  end

  def update
    @goal = Goal.find_by(id: params[:id])
    @user = User.find_by(id: @goal.user_id)

    @goal.update(goal_params)
    redirect_to user_goals_url(@user)
  end

  def show
    @goal = Goal.find_by(id: params[:id])

    if @goal
      render :show
    else
      @goal.errors.full_messages
    end
  end

  def destroy
    @goal = Goal.find_by(id: params[:id])

    @goal.destroy
    @goal
  end

  private

  def goal_params
    params.require(:goal).permit(:name, :public, :complete, :user_id)
  end
end

W10D2/aspiration_list/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user.nil?
      render :new
    else
      login!(@user)
      redirect_to user_url(@user)
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

W10D2/aspiration_list/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login

  def index
    @users = User.all

    render :index
  end

  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_url(@user)
    else
      redirect_to users_url
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @goals = Goal.where(id: @user.id)
    
    if @user
      render :show
    else
      redirect_to users_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W10D2/aspiration_list/app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form action="<%= user_goal_url(@goal) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="goal_name">Name:</label>
  <input id="goal_name" type="text" name="goal[name]">

  <label for="goal_user_id">User:</label>
  
  <input type="radio" id="goal_private" name="goal[private]">
  <label for="goal_private">Private</label>

  <input type="submit" value="Edit Goal">
</form>

W10D2/aspiration_list/app/views/goals/index.html.erb
<h1><%= @user.username %> Goals!</h1>

<ul>
<% @goals.each do |goal| %>
  <li><%= goal.name %></li>
  <li>
    <form action="<%= goal_url %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="submit" value="Delete <%= goal.name %> Goal">
    </form>
  </li>
<% end %>
</ul>

W10D2/aspiration_list/app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action="<%= goals_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label for="goal_name">Name:</label>
  <input id="goal_name" type="text" name="goal[name]">

  <label for="goal_user_id">User:</label>
  <select name="goal[user_id]" id="goal_user_id">
    <% @users.each do |user| %>
      <option value="<%= user.id %>"><%= user.username %></option>
    <% end %>
  </select>

  <input type="radio" id="goal_private" name="goal[private]">
  <label for="goal_private">Private</label>

  <input type="submit" value="Submit New Goal">
</form>

W10D2/aspiration_list/app/views/goals/show.html.erb
<h1>Show page for Goal</h1>

W10D2/aspiration_list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AspirationList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
      <% if !current_user.nil? %>
        <li>Logged In As:<%= current_user.username %></li>
        <li>
          <form action="<%= session_url %>" method="POST">
            <input type="hidden" name="_method" value="DELETE">
            <input 
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">

            <input type="submit" value="Log Out">
          </form>
        </li>
      <% else %>
        <li> 
          <form action="<%= new_session_url %>" method="GET">
            <input 
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">
            <input type="submit" value="Sign In"
          </form>
        </li>
        <li>
          <form action="<%= new_user_url %>" method="GET">
            <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">

            <input type="submit" value="Sign Up">
          </form>
        </li>
      <% end %>
      <ul>
    </header>
    <%= yield %>
  </body>
</html>

W10D2/aspiration_list/app/views/users/index.html.erb
<h1>Users</h1>

<ul>
<% @users.each do |user| %>
  <li><%= user.username %></li>
<% end %>
</ul>

W10D2/aspiration_list/app/views/users/new.html.erb
<h1>New User Page!</h1>


<form action="<%= users_url %>" method="POST">
  <input 
    type="hidden"
    name="authenticity_token"
    value="<% form_authenticity_token %>">

  <label for="user_username">Username:</label>
  <input type="text" name="user[username]" id="user_username">

  <label for="user_password">Password:</label>
  <input type="text" name="user[password]" id="user_password">

  <input type="submit" value="create user">
</form>

W10D2/aspiration_list/app/views/users/show.html.erb
<h1>Hello <%= @user.username %> </h1>

<ul>
<% @goals.each do |goal| %>
  <li><%= goal.name %></li>
<% end %>
</ul>